/**
 * The Especialidades enumeration.
 */
export enum Especialidades {
    DERMATOLOGIA = 'DERMATOLOGIA',
    GINECOLOGIA = 'GINECOLOGIA',
    EMERGENCIAS = 'EMERGENCIAS',
    OFTALMOLOGIA = 'OFTALMOLOGIA',
    OTORRINOLARGOLOGIA = 'OTORRINOLARGOLOGIA',
    CLINICO = 'CLINICO',
    BIOQUIMICA = 'BIOQUIMICA',
    FARMACOLOGIA = 'FARMACOLOGIA',
    INMUNOLOGIA = 'INMUNOLOGIA',
    RADIOLOGIA = 'RADIOLOGIA',
    TRAUMATOLOGIA = 'TRAUMATOLOGIA',
}
